### ISSUE TITLE
[BUG] Client.version is null

### ISSUE THREAD

**Issue by FabrizioCoder** [TheDrone7/shieldbow#17]
**Screenshots**
![image](https://user-images.githubusercontent.com/74118796/182470381-0fe56f17-ff0c-4e19-97df-6a43b38d284c.png)
![image](https://user-images.githubusercontent.com/74118796/182470588-c9b181ef-4fb7-4798-8000-76f0beb7c22b.png)

**Comment by MrBartusek** [comment]
Do you run [`Client.initialize()`](https://thedrone7.github.io/shieldbow/api/Client.html#initialize-options)? can you give full code snippet?

**Comment by FabrizioCoder** [comment]
> Do you run [`Client.initialize()`](https://thedrone7.github.io/shieldbow/api/Client.html#initialize-options)? can you give full code snippet?

right, i forgot about that. it's working now, thanks
