### ISSUE TITLE
No way to see stabile docs

### ISSUE THREAD

**Issue by MrBartusek** [TheDrone7/shieldbow#18]
Currently, docs changes are deployed every commit to https://thedrone7.github.io/shieldbow/. That means these are the docs for the current master and there is no way to see docs for lastest stabile `v1.3.0`

**Comment by TheDrone7** [comment]
Yeah, that's known. I have been reading about Github actions to automate this so they only get published when I create a new release instead of just commits.

It's going to be one of the things in my next push today.
