### ISSUE TITLE
Improper cache checks throughout project

### ISSUE THREAD

**Issue by MrBartusek** [TheDrone7/shieldbow#24]
This project uses many improper cache checks. There are many conditions made like that:

https://github.com/TheDrone7/shieldbow/blob/1acea363d9888a3a4ae9bfd185c0319bd8b73cb1/src/managers/ChampionManager.ts#L154-L157

There should be a check to verify if the champions cache is complete and if not, re-fetch all champions (or only these missing ones). Right now it checks if there is at least one champion in the cache.

Look at this sample:

```ts
import { Client } from './dist/client.js';

const client = new Client(''); // Key not required
client
  .initialize({
    region: 'euw'
  })
  .then(async () => {
    //await client.champions.fetch('Heimerdinger');
    const kayn = await client.champions.findByName('Kayn');
    console.log(kayn.name);
  });
```

This code work:
```
λ node demo.mjs
Kayn
````

But uncommenting Heimerdinger fetch breaks it:
```
λ node demo.mjs
file:///C:/dev/shieldbow/demo.mjs:11
    console.log(kayn.name);
                     ^

TypeError: Cannot read properties of undefined (reading 'name')
    at file:///C:/dev/shieldbow/demo.mjs:11:22
    at processTicksAndRejections (node:internal/process/task_queues:96:5)|
```

There are nine of these checks:

![image](https://user-images.githubusercontent.com/23432278/183259666-d0e14312-da9a-41e0-836f-2769f2e4315f.png)

**Comment by TheDrone7** [comment]
This can be certainly improved but only for champions, since the other stuff is just a single file anyways.

**Comment by TheDrone7** [comment]
The commit https://github.com/TheDrone7/shieldbow/commit/934921926d9acd5d34ac9a7f59f460c79d61696f should address this issue.
