### ISSUE TITLE
Better formatting for Api Errors

### ISSUE THREAD

**Issue by MrBartusek** [TheDrone7/shieldbow#26]
Currently, when [ApiError](https://thedrone7.github.io/shieldbow/api/ApiError.html) is thrown it dumps the whole object that takes a couple hundreds of lines. 99% of those is useless stuff that nobody needs and it also logs API tokens. There can be a nicer format like [one I have here](https://github.com/MrBartusek/ClashCalendar/blob/master/src/utils.ts#L44-L56)

**Comment by TheDrone7** [comment]
API errors always are supposed to have a full response object. Though there does exist a shorter helpful `message` property on all errors.

For instance, try this

```js
const { Client } = require('../dist');

const client = new Client('');

client
  .initialize({
    cache: false,
    fetch: false
  })
  .then(async () => {
    const summoner = await client.summoners.fetchBySummonerName('TheDrone7').catch((e) => {
      console.log(e.message);
    });
    console.log(summoner);
  });

```

You will see the following output
```
401:: Unauthorized
No API key was found, please make sure you're providing one.
undefined
```
