### ISSUE TITLE
Add sprite icon information for Champion

### ISSUE THREAD

**Issue by MissUwuieTime** [TheDrone7/shieldbow#32]
**Is your feature request related to a problem? Please describe.**
I have been using `ChampionManager` to fetch icons of champions to serve in a REST api. While this approach has worked good, it is resource intensive as many requests have to be made from the front-end for each champion (often 100-200 requests for a webpage to fetch each champion icon). :c

**Describe the solution you'd like**
Have the `Champion` instance provide sprite information parsed from ddragon. For example:
```typescript
const champion = await client.champions.fetchByName('Sona');
// Use sprite information goodies <3
champion.sprite.icon;             // 'https://ddragon.leagueoflegends.com/cdn/12.11.1/img/sprite/champion3.png'
champion.sprite.coordinates;      // { x: 336, y: 96}
champion.sprite.size;             // { w: 48, h: 48}
```

**Describe alternatives you've considered**
Caching helps mitigate this, but each icon has to be loaded individually still. Using the sprite information (spritesheet url, coordinates, size) would help reduce the requests required and reduce loading times for the front-end (yay).

**Comment by TheDrone7** [comment]
Unfortunately, RIOT has oofed up my keys so I cannot test the changes I am making so no changes are being made yet. Will get to these as soon as they fix my keys.
