### ISSUE TITLE
Add SEA regions

### ISSUE THREAD

**Issue by DarkIntaqt** [TheDrone7/shieldbow#40]
https://twitter.com/RiotGamesDevRel/status/1611143167985987590
It would be pretty nice to use the new SEA regions in shieldbow, maybe even before v2.

**Comment by TheDrone7** [comment]
There are already some v2 changes in `main` so it would definitely have to wait till v2 for these, but that shouldn't be much longer now.

**Comment by TheDrone7** [comment]
Addressed in v2.0, officially released.

**Comment by DarkIntaqt** [comment]
🎉
