### ISSUE TITLE
[BUG] Participant summoner spells return undefined

### ISSUE THREAD

**Issue by ClaraSmyth** [TheDrone7/shieldbow#42]
**Describe the bug**
When checking a participant of a match their summoner spells return undefined.

**To Reproduce**
```ts
client.initialize({
  region: 'euw' // defaults to 'na'
}).then(async () => {
  const match = await client.matches.fetch('EUW1_6269532573');

  const blueTeam = match.teams.get('blue');
  const playerOneSpells = blueTeam?.participants[0]?.summonerSpells;
  const spellD = playerOneSpells?.get('D');
  const spellF = playerOneSpells?.get('F');

  console.log(spellD); // Returns undefined
  console.log(spellF); // Returns undefined
});
```

**Expected behavior**
Summoner spells should return with a SummonerSpell and not undefined.

**Desktop (please complete the following information):**
 - OS: EndeavourOS Linux
 - Node.JS version: v19.6.0
 - Library version: 1.6.0
- Typescript version: 4.7.4

**Additional context**

The issue is caused in the src/structures/Participant.ts
Line: 610/611

```ts
  this.summonerSpells.set('D', client.summonerSpells.cache.get(data.summoner1Id.toString())!);
  this.summonerSpells.set('F', client.summonerSpells.cache.get(data.summoner2Id.toString())!);
```
Problem is data.summoner1Id and data.summoner2Id are a SummonerSpell key (e.g 4 for Flash) but the keys in the cache are SummonerSpell IDs (e.g. SummonerFlash). 

I was able to fix it with this code block but unsure if its an ideal fix.
```ts
  this.summonerSpells.set('D', client.summonerSpells.cache.find((s) => s.key === data.summoner1Id)!);
  this.summonerSpells.set('F', client.summonerSpells.cache.find((s) => s.key === data.summoner2Id)!);
```

**Comment by TheDrone7** [comment]
Addressed in v2.0, officially released.
