### ISSUE TITLE
Add support for getTopChampionMasteries 

### ISSUE THREAD

**Issue by t-miller** [TheDrone7/shieldbow#43]
**Is your feature request related to a problem? Please describe.**
I would like an implementation of Riot's getTopChampionMasteries endpoint so I can return the top `n` number of champion masteries for a summoner 

**Describe the solution you'd like**
I'd like a method I can call with an integer value that returns the top `n` champion masteries (e.g., `summoner.championMastery.getTop(3)`) that is backed by the linked getTopChampionMasteries endpoint

**Describe alternatives you've considered**
Currently I'm doing `Promise.all([
		summoner.championMastery.highest(0),
		summoner.championMastery.highest(1),
		summoner.championMastery.highest(2)
	])` to get the top 3

**Additional context**
[getTopChampionMasteries documentation](https://developer.riotgames.com/apis#champion-mastery-v4/GET_getTopChampionMasteries)

**Comment by TheDrone7** [comment]
You would have to continue using `.highest` anyways. Right now it does use the `getAllChampionMasteries` method, but in `v2` its implementation will be replaced with the `getTopChampionMasteries` method, however, as a user of shieldbow, your code should look exactly the same.

side note: One of the biggest hurdles in releasing v2 was a new rate limiter which was just finished. With a few polish changes and updates, v2 will release this fix soon.

**Comment by TheDrone7** [comment]
Addressed in v2.0, officially released.
