### ISSUE TITLE
[BUG] Missing information in _rawtooltip 

### ISSUE THREAD

**Issue by BmElectro** [TheDrone7/shieldbow#5]
Bug Description:

Champions that have forms e.g. (Elise, Gnar) are missing one of their forms information in _rawtooltip of a spell

Example _rawtooltip of Nidalee Q:

<keywordMajor>Human Form:</keywordMajor> Nidalee throws her javelin, dealing <magicDamage>70/90/110/130/150 (+50% AP) magic damage</magicDamage>, increased up to <magicDamage>210/270/330/390/450 (+150% AP) magic damage</magicDamage> based on distance flown.

As seen in the example above the information for "cougar" form is missing.

**Comment by TheDrone7** [comment]
The problem is, I checked the raw data, and unfortunately data dragon has only this much data so can't really do much about it.
