### ISSUE TITLE
[BUG] Potential Test Case Failure For Match Timeline

### ISSUE THREAD

**Issue by DarkIntaqt** [TheDrone7/shieldbow#51]
https://github.com/TheDrone7/shieldbow/blob/33b20373c6b9c5fdee7efe1ada6cd763902e645a/tests/match.test.ts#L47

There isn't always the need of 10 summoners in a game, for example bot games. Therefore, this test case can unexpectedly fail.

**Comment by TheDrone7** [comment]
It uses my matches so its safe :KEKW:
