### ISSUE TITLE
[BUG] Setting a ManagersConfig with undefined `api` for cache or storage property of ClientConfig may throw a TypeError upon affected API call

### ISSUE THREAD

**Issue by BlossomiShymae** [TheDrone7/shieldbow#54]
**Describe the bug**
Setting the `cache` or `storage` property of a `ClientConfig` with a `ManagersConfig` that has an undefined `api` will result in `TypeError: Cannot read properties of undefined` of the affected API call.

**To Reproduce**
1. Install `shieldbow 2.0.4`.
2. Initialize the client with a partial object for `cache` or `storage` that neither enables nor disables API.
3. Call an API that was neither enabled nor disabled for `cache` or `storage` options.
4. Receive a `TypeError`.

**Expected behavior**
Expected to run without any errors.

**Error**
The `reading` part is API dependent
```
TypeError: Cannot read properties of undefined (reading 'summoner')
    at parseFetchOptions (C:\Users\Maevie\Desktop\shieldbow_sandbox\node_modules\shieldbow\src\util\parseFetchOptions.ts:47:35)
    at SummonerManager.fetchBySummonerName (C:\Users\Maevie\Desktop\shieldbow_sandbox\node_modules\shieldbow\src\managers\SummonerManager.ts:119:35)
    at main (C:\Users\Maevie\Desktop\shieldbow_sandbox\index.ts:32:45)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node.JS version: 16.15.1
 - Library version: 2.0.4
- Typescript version: 5.0.2

**Additional context**

```ts
// cache
await client.initialize({
      region: "na",
      cache: {
        enable: {
          dragon: {
            champions: true
          }
        }
      }
});

const summoner = await client.summoners.fetchBySummonerName("uwuie time");
// TypeError: Cannot read properties of undefined (reading 'summoner')


// storage
await client.initialize({
      region: "na",
      storage: {
        enable: {
            dragon: {
                champions: true,
            }
        }
      }
});

const summoner = await client.summoners.fetchBySummonerName("uwuie time");
// TypeError: Cannot read properties of undefined (reading 'summoner')
```

Doing something like this will not bring up any errors:
```ts
await client.initialize({
      region: "na",
      cache: {
        enable: {
          api: {
            summoner: false
          },
          dragon: {
            champions: true
          }
        }
      },
});

const summoner = await client.summoners.fetchBySummonerName("uwuie time");
const league = await client.leagues.fetchByLeagueId(summoner.id); 
```

Something like this will:
```ts
await client.initialize({
      region: "na",
      cache: {
        enable: {
          dragon: {
            champions: true
          }
        }
      },
});

const summoner = await client.summoners.fetchBySummonerName("uwuie time"); 
// TypeError: Cannot read properties of undefined (reading 'summoner')
const league = await client.leagues.fetch(summoner.id); 
```

**Notes**
Unsure if this affects `dragon` as I haven't really tested that.

**Comment by BlossomiShymae** [comment]
I will just totes say "Yep I could have just set `api` or `dragon` to true or false like a normal person". Oh well. :3

**Comment by DarkIntaqt** [comment]
Is this related to #53?

**Comment by BlossomiShymae** [comment]
> Is this related to #53?

I actually was trying to troubleshoot the same person's problem from a Discord thread before they submitted an issue (likely yep). (//▽//)
