### ISSUE TITLE
Change Item fromIds and intoIds from private to public.

### ISSUE THREAD

**Issue by ClaraSmyth** [TheDrone7/shieldbow#55]
**Is your feature request related to a problem? Please describe.**
Essentially without access to the fromIds and intoIds on an Item I don't believe its possible to visually represent an Items entire build path when it contains multiple of the same component. This happens because the .from() and .into() methods don't return duplicate items.

**Describe the solution you'd like**
Change Item fromIds and intoIds from private to public so the compiler doesn't get angry when you access them. 

**Describe alternatives you've considered**
Alternatively .from() and .into() could include the duplicate item but I feel like public access to the ids is preferable.

**Additional context**

Example of what I mean:
```ts
      // Using Ardent Censor as an example which is made up of 2 Amp Tomes and a Forbidden Idol
      const item = await client.items.fetch('3504');
      const from = await item.from();

      console.log(from); // Returns ['1052' => Item, '3114' => Item]
      // The item is made up of 3 components but from only contains 2 because there is a duplicate.

      console.log(item.fromIds); // Returns [ '1052', '3114', '1052' ]
      // This contains the correct component structure to display them but the compiler isn't happy.
      // Property 'fromIds' is private and only accessible within class 'Item'
```

I can't come up with another way to easily display an Items entire component structure but its possible I'm missing something.

**Comment by BlossomiShymae** [comment]
You can try doing this as a temporary workaround for now (not really intended though, hehe).
```typescript
const item = await client.items.fetch("3504");
// Use index operator instead, compiler not angy >:3
const ids: string[] = item["fromIds"];

// => [ '1052', '3114', '1052' ]
console.log(ids);
```

I agree that information should be public though. o.o

**Comment by TheDrone7** [comment]
Thanks for pointing the issue out! However, instead of making the IDs public, I would rather have `from` and `to` into Arrays instead of a Collection, as that was the whole idea behind shieldbow, to get related objects easier instead of having to deal with IDs. If you need IDs, then you could just access them from the objects

**Comment by TheDrone7** [comment]
Although, I am currently working on improving the debug logs as they are all over the place for now, so in the meantime I would recommend what @BlossomiShymae suggested above.
