### ISSUE TITLE
Add Emerald tier for League entries

### ISSUE THREAD

**Issue by BlossomiShymae** [TheDrone7/shieldbow#60]
https://www.leagueoflegends.com/en-us/news/game-updates/what-s-next-for-ranked/

Probs after July 17-ish, when Split 2 starts, that this new ranked tier will be present in `league-v4`. :3

EDIT: Removed double negative, omg. ><

**Comment by TheDrone7** [comment]
Might need another issue to migrate league manager to league-v4 instead of league-exp-v4

**Comment by TheDrone7** [comment]
Agreed, these should be added to v2 especially since v3 will probably take a few months to rewrite from scratch.
