### ISSUE TITLE
[BUG] Invalid TS declaration files on Linux

### ISSUE THREAD

**Issue by MrBartusek** [TheDrone7/shieldbow#7]
**Describe the bug**
Hey, there is some issue with declaration files on filesystems that respect uppercases like Linux. I don't have any problems while a compiiling project with this lib on my Windows machine but as soon as I get my stuff to the Linux server or GH actions it fails with this error:

![image](https://user-images.githubusercontent.com/23432278/179876310-b2365b25-2c75-4667-a994-eccb214b00f6.png)

Failed run of Github Actions:
https://github.com/MrBartusek/ClashCalendar/runs/7420804958?check_suite_focus=true

![image](https://user-images.githubusercontent.com/23432278/179876338-3e75bcf2-1e8e-40a5-ae92-c80b00d5f6a4.png)

It seams like declarations on npm package have invalid file names.

All these should be uppercase `Image` not `image`.
![image](https://user-images.githubusercontent.com/23432278/179876475-fb456ece-6186-40bc-8604-28e6eb718295.png)

Same with `Champion` that is `champion`  and  `Item` that is `item`.

This doesn't cause an issue on Windows since it doesn't respect uppercase letters in filenames but fails on Linux since it does.

**Comment by MrBartusek** [comment]
It seems like it was fixed in https://github.com/TheDrone7/shieldbow/commit/840cc6046c13bb5297f877db5b5c975da14546c3 however files on npm for `v1.3.0` are still invalid for some reason

**Comment by TheDrone7** [comment]
This is really weird cuz I actually just tried using it on Linux and it worked just fine. The PR did fix the problem for me at least.

**Comment by MrBartusek** [comment]
> This is really weird cuz I actually just tried using it on Linux and it worked just fine. The commit did fix the problem for me at least.

I've just cleared the cache and installed it once again, files are still invalid 

![image](https://user-images.githubusercontent.com/23432278/181933958-1f2f7895-e550-4898-acf4-3885962350e2.png)

**Comment by TheDrone7** [comment]
I really am unsure what's going on here, I have tried on my local machine, running Ubuntu 21.04 and on replit - https://replit.com/@TheDrone7/AggressiveGreatLevels which adds even more confusion to why this might be happening. I'll spend some time searching but I really am unsure what could be the issue here.

**Comment by MrBartusek** [comment]
@TheDrone7 actually this replit runs on JS while this is TS declaration issue

**Comment by SalmonMode** [comment]
@TheDrone7 found the issue. 

![image](https://user-images.githubusercontent.com/13908130/182917571-1c788142-44bc-4e97-aecc-9ae21a6ad5b3.png)

![image](https://user-images.githubusercontent.com/13908130/182917514-8ec9cbe0-d736-4367-9245-c7d6701b00dd.png)

For some reason, the file names are lowercase on the version uploaded to npm (should be PascalCase). Changing them manually resolved my issue.

I cloned and ran the build command myself, and it built them with properly cased file names, so I'm not sure what happened. But that definitely seems to be the core issue.

**Comment by TheDrone7** [comment]
@SalmonMode that is the issue but I'm not sure why the npm file name case did not update. There has been a newer version published after this was fixed for GitHub.

**Comment by SalmonMode** [comment]
Oh my bad haha. Totally missed that part int he original post.

**Comment by TheDrone7** [comment]
v1.4.0 just got released, could you confirm if this is still an issue?

**Comment by MrBartusek** [comment]
Yup, it got fixed!
