### ISSUE TITLE
[BUG] Arena queue id and map Id is missing 

### ISSUE THREAD

**Issue by DarkIntaqt** [TheDrone7/shieldbow#70]
**Describe the bug**
The queueId for Arena is missing (1700), as well as the map Id. 

This issue occurred whilst I tried to fix #69. <= I wanted to filter out games by ARENA (queueId or map), the efficient way), to fix Arena bug. 

Might consider to pull queueIds from cdragon instead (https://github.com/RiotGames/developer-relations/issues/792)

**Comment by TheDrone7** [comment]
reeeeeeeeeeeeeeee RIIIOOOOOT

**Comment by TheDrone7** [comment]
Honestly debating if I should completely ignore data dragon for v3

**Comment by TheDrone7** [comment]
They were added, resolving
