### ISSUE TITLE
[BUG] package.json and GitHub release version mismatch with NPM

### ISSUE THREAD

**Issue by raitono** [TheDrone7/shieldbow#74]
**Describe the bug**
package.json and GitHub release version mismatch with NPM

**Expected behavior**
package.json and GitHub release (if applicable) versions match latest published NPM version

**Additional context**
package.json and GitHub releases are showing v2.1.1 and NPM shows v2.2.0.

**Comment by TheDrone7** [comment]
This is known because the latest npm version was force-published, it is not a bug but a known issue with the rate limiter. Resolution is part of v3
