### ISSUE TITLE
SSR deploys ain't working properly

### ISSUE THREAD

**Issue by proudyy** [TheDrone7/shieldbow#87]
Whenever a SSR [astro](astro.build) project is being tried to deployed to a cloudflare page, a vite SSR error appears.
![cf page shieldbow vite error](https://github.com/TheDrone7/shieldbow/assets/95212023/be833342-ec49-4ac3-851e-4ad137aa5069)

Trying the approach inside the error message out inside the astro-configuration doesn't seem to help out...
![astro vite no external ssr config](https://github.com/TheDrone7/shieldbow/assets/95212023/c9400db2-54a9-4af4-b4ac-1432c62d5d16)

Reproducing this is kinda hard in my opinion as my cloudflare page got a prebuilt setup which automatically pushes new commits from the github repository acting as a github action. However, there's no github deployment workflow yml-configuration for this strangely, so I assume this happens purely internal. A way to reproduce it would be to create a cloudflare page on your own as it's supporting a variety of well known web frameworks, this seems to be necessary here as I can't find any other way to reproduce this error in local environment. 

This is why I'm very confused because building the project locally works like a charm but once the function is being run by cloudflare, it fails with the shown error inside the logs.
Here's the current build command shown in a small code snippet:
![npm build cmd](https://github.com/TheDrone7/shieldbow/assets/95212023/ac4d7fac-0ffe-47d2-8cc4-22134cefc00e)

**Comment by TheDrone7** [comment]
shieldbow works on the server-side only. Cloudflare workers/pages is serverless
